<footer class="page-footer">
    <div class="footer content">
        <div class="custom-footer-container-middle">
            <div class="footer-section-one links footer-col1">
                <div class="footer_section_title footer-accordian-title">FIND US</div>
                <div class="footer_section_content footer-accordian-content">
                    <p class="f_location"><span class="content_loc">4809 Buford Hwy Atlanta, <br>GA, US 30341</span></p>
                    <p class="f_mail"><a class="loc-mail" href="mailto:sales.info@lacns.com">Sales.info@lacns.com</a>
                    </p>
                    <p class="f_tel"><a class="loc-tel" href="tel:+1 770-220-0108">+1 770-220-0108</a></p>
                </div>
            </div>
            <div class="footer-section-two links footer-col1">
                <div class="footer_section_title footer-accordian-title">CATEGORIES</div>
                <div class="footer_section_content footer-accordian-content">
                    <ul class="prod_list">
                        <li><a href="#">Makeup </a></li>
                        <li><a href="#">Skin Care </a></li>
                        <li><a href="#">Bath and Body</a></li>
                        <li><a href="#">Brushes</a></li>
                        <li><a href="#">Hair</a></li>
                        <li><a href="#">View All</a></li>
                    </ul>
                </div>
            </div>
            <div class="footer-section-three links footer-col1">
                <div class="footer_section_title footer-accordian-title">INFOMATION</div>
                <div class="footer_section_content footer-accordian-content">
                    <ul class="prod_list">
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Contact Us</a></li>
                        <li><a href="#">Terms Conditions</a></li>
                        <li><a href="#">Returns Exchanges</a></li>
                        <li><a href="#">Shipping Delivery</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
            <div class="footer-section-four links footer-col1">
                <div class="footer_section_title footer-accordian-title">QUICK LINKS</div>
                <div class="footer_section_content footer-accordian-content">
                    <ul class="prod_list">
                        <li><a href="#">Store Location</a></li>
                        <li><a href="#">My Account</a></li>
                        <li><a href="#">Orders Tracking</a></li>
                        <li><a href="#">Style Guide</a></li>
                        <li><a href="#">FAQs</a></li>
                    </ul>
                </div>
            </div>
            <div class="footer-section-five links footer-col1">
                <div class="block newsletter">
                    <div class="footer_section_title footer-accordian-title">NEWSLETTER</div>
                    <div class="footer_section_content footer-accordian-content">
                        <div class="subtitle">Join our list to save 10% off your next purchase and get the latest on new
                            arrivals.</div>
                        <div class="content">
                            <form class="form subscribe" novalidate="novalidate"
                                action="https://lanails.cptestserver.com/newsletter/subscriber/new/" method="post"
                                id="newsletter-validate-detail">
                                <div class="field newsletter">
                                    <div class="control">
                                        <label for="newsletter">
                                            <span class="label">
                                                Sign Up for Our Newsletter: </span>
                                            <input name="email" type="email" id="newsletter"
                                                placeholder="Enter Your Email"
                                                data-validate="{required:true, 'validate-email':true}">
                                        </label>
                                    </div>
                                </div>
                                <div class="actions">
                                    <button class="action subscribe primary" title="Subscribe" type="submit"
                                        aria-label="Subscribe">
                                        <span>Subscribe</span>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-last"><small class="copyright">
                <span>Copyright © 2022-present Magento, Inc. All rights reserved.</span>
            </small>
            <div class="custom-links">
                <div class="social-links-footer">
                    <ul>
                        <li class="list1"><span class="fac-icon"></span> <a href="#">Facebook</a></li>
                        <li class="list2"><span class="tweet-icon"></span><a href="#">Twitter</a></li>
                        <li class="list3"><span class="insta-icon"></span><a href="#">Instagram</a></li>
                    </ul>
                </div>
                <div class="payment-icons"><img src="https://lanails.cptestserver.com/media/wysiwyg/discover.png"
                        alt="Discover"> <img src="https://lanails.cptestserver.com/media/wysiwyg/american-ex.png"
                        alt="American Express"> <img src="https://lanails.cptestserver.com/media/wysiwyg/paypal.png"
                        alt="Paypal"> <img src="https://lanails.cptestserver.com/media/wysiwyg/mastercard.png"
                        alt="Mastercard"></div>
            </div>
        </div>
    </div>
</footer>